spring:
  application:
    name: item-service
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 192.168.43.170
    port: 5672
    username: admin
    password: admin
    
server:
  port: 8001
  
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:2001/eureka,http://127.0.0.1:2002/eureka